channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=25.3
- pip:
  - mlflow==3.6.0
  - cloudpickle==3.1.2
  - numpy==2.3.2
  - pandas==2.3.2
  - psutil==7.0.0
  - pyarrow==22.0.0
  - scikit-learn==1.7.1
  - scipy==1.16.1
name: mlflow-env
